import { Group } from './../types/Group'
export const RECOMMEND_GROUP_DATA = [
  {
    id: '1',
    users: [
      {
        id: '1',
        imageForCard: '/user1-2.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '2',
        imageForCard: '/user3-2.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '2',
    users: [
      {
        id: '3',
        imageForCard: '/user1-3.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '4',
        imageForCard: '/user2-2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '5',
        imageForCard: '/user3-3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '3',
    users: [
      {
        id: '6',
        imageForCard: '/user1-3.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '7',
        imageForCard: '/user3-4.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
      {
        id: '8',
        imageForCard: '/user2-2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '9',
        imageForCard: '/user4.png',
        imagesForProfile: [
          '/user4-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'えみり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '4',
    users: [
      {
        id: '10',
        imageForCard: '/user1-2.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '11',
        imageForCard: '/user3-2.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '5',
    users: [
      {
        id: '12',
        imageForCard: '/user1-2.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '13',
        imageForCard: '/user3-2.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '6',
    users: [
      {
        id: '14',
        imageForCard: '/user1-3.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '15',
        imageForCard: '/user2-2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '16',
        imageForCard: '/user3-3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '7',
    users: [
      {
        id: '17',
        imageForCard: '/user1-3.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '18',
        imageForCard: '/user3-4.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
      {
        id: '19',
        imageForCard: '/user2-2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '20',
        imageForCard: '/user4.png',
        imagesForProfile: [
          '/user4-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'えみり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '8',
    users: [
      {
        id: '21',
        imageForCard: '/user1-2.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '22',
        imageForCard: '/user3-2.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
]

export const PICK_UP_GROUP_DATA: Group[] = [
  {
    id: '9',
    users: [
      {
        id: '23',
        imageForCard: '/user1.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '24',
        imageForCard: '/user2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '25',
        imageForCard: '/user3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '10',
    users: [
      {
        id: '26',
        imageForCard: '/user1.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '27',
        imageForCard: '/user2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '28',
        imageForCard: '/user3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '11',
    users: [
      {
        id: '29',
        imageForCard: '/user1.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '30',
        imageForCard: '/user2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '31',
        imageForCard: '/user3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '12',
    users: [
      {
        id: '23',
        imageForCard: '/user1.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '24',
        imageForCard: '/user2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '25',
        imageForCard: '/user3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '13',
    users: [
      {
        id: '26',
        imageForCard: '/user1.png',
        imagesForProfile: [
          '/user1-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '27',
        imageForCard: '/user2.png',
        imagesForProfile: [
          '/user2-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '28',
        imageForCard: '/user3.png',
        imagesForProfile: [
          '/user3-large.png',
          '/user2-large.png',
          '/user3-large.png',
          '/user4-large.png',
          '/user1-large.png',
          '/user2-large.png',
        ],
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
]
