export const OWN_GROUP_DATA = [
  {
    id: '1',
    users: [
      {
        id: '1',
        imageForCard: '/user5-rect.png',
        imageForProfile: '',
        name: 'KAKERU',
        age: '28',
        job: 'IT関係',
        sex: 0,
      },
      {
        id: '2',
        imageForCard: '/user6-rect.png',
        imageForProfile: '',
        name: 'Shun',
        age: '27',
        job: '広告営業',
        sex: 0,
      },
      {
        id: '3',
        imageForCard: '/user7-rect.png',
        imageForProfile: '',
        name: 'ODA',
        age: '28',
        job: 'エンジニア',
        sex: 0,
      },
    ],
    goodGroups: [
      {
        id: '1',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
      {
        id: '2',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
      {
        id: '3',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
      {
        id: '4',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '/user1-large.png',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '/user2-large.png',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '/user3-large.png',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
    ],
  },
  {
    id: '2',
    users: [
      {
        id: '4',
        imageForCard: '/user5-square.png',
        imageForProfile: '',
        name: 'KAKERU',
        age: '28',
        job: 'IT関係',
        sex: 0,
      },
      {
        id: '5',
        imageForCard: '/user6-square.png',
        imageForProfile: '',
        name: 'Shun',
        age: '27',
        job: '広告営業',
        sex: 0,
      },
    ],
    goodGroups: [
      {
        id: '1',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
      {
        id: '2',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
      {
        id: '3',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
      {
        id: '4',
        users: [
          {
            id: '1',
            imageForCard: '/user1.png',
            imageForProfile: '/user1-large.png',
            imageForIcon: '',
            name: 'あかね',
            age: '25',
            job: '歯科助手',
            sex: 1,
          },
          {
            id: '2',
            imageForCard: '/user2.png',
            imageForProfile: '/user2-large.png',
            imageForIcon: '',
            name: 'かな',
            age: '27',
            job: '広告営業',
            sex: 1,
          },
          {
            id: '3',
            imageForCard: '/user3.png',
            imageForProfile: '/user3-large.png',
            imageForIcon: '',
            name: 'ゆり',
            age: '25',
            job: '美容師',
            sex: 1,
          },
        ],
      },
    ],
  },
  {
    id: '3',
    users: [
      {
        id: '6',
        imageForCard: '/user5-rect.png',
        imageForProfile: '',
        name: 'KAKERU',
        age: '28',
        job: 'IT関係',
        sex: 0,
      },
      {
        id: '7',
        imageForCard: '/user6-rect.png',
        imageForProfile: '',
        name: 'Shun',
        age: '27',
        job: '広告営業',
        sex: 0,
      },
      {
        id: '8',
        imageForCard: '/user7-rect.png',
        imageForProfile: '',
        name: 'ODA',
        age: '28',
        job: 'エンジニア',
        sex: 0,
      },
    ],
  },
  {
    id: '4',
    users: [
      {
        id: '6',
        imageForCard: '/user5-rect.png',
        imageForProfile: '',
        name: 'KAKERU',
        age: '28',
        job: 'IT関係',
        sex: 0,
      },
      {
        id: '7',
        imageForCard: '/user6-rect.png',
        imageForProfile: '',
        name: 'Shun',
        age: '27',
        job: '広告営業',
        sex: 0,
      },
      {
        id: '8',
        imageForCard: '/user7-rect.png',
        imageForProfile: '',
        name: 'ODA',
        age: '28',
        job: 'エンジニア',
        sex: 0,
      },
    ],
  },
]

export const GOOD_GROUP_DATA = [
  {
    id: '1',
    users: [
      {
        id: '1',
        imageForCard: '/user1.png',
        imageForProfile: '/user1-large.png',
        imageForIcon: '',
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '2',
        imageForCard: '/user2.png',
        imageForProfile: '/user2-large.png',
        imageForIcon: '',
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '3',
        imageForCard: '/user3.png',
        imageForProfile: '/user3-large.png',
        imageForIcon: '',
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '2',
    users: [
      {
        id: '1',
        imageForCard: '/user1.png',
        imageForProfile: '/user1-large.png',
        imageForIcon: '',
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '2',
        imageForCard: '/user2.png',
        imageForProfile: '/user2-large.png',
        imageForIcon: '',
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '3',
        imageForCard: '/user3.png',
        imageForProfile: '/user3-large.png',
        imageForIcon: '',
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '3',
    users: [
      {
        id: '1',
        imageForCard: '/user1.png',
        imageForProfile: '/user1-large.png',
        imageForIcon: '',
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '2',
        imageForCard: '/user2.png',
        imageForProfile: '/user2-large.png',
        imageForIcon: '',
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '3',
        imageForCard: '/user3.png',
        imageForProfile: '/user3-large.png',
        imageForIcon: '',
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
  {
    id: '4',
    users: [
      {
        id: '1',
        imageForCard: '/user1.png',
        imageForProfile: '/user1-large.png',
        imageForIcon: '',
        name: 'あかね',
        age: '25',
        job: '歯科助手',
        sex: 1,
      },
      {
        id: '2',
        imageForCard: '/user2.png',
        imageForProfile: '/user2-large.png',
        imageForIcon: '',
        name: 'かな',
        age: '27',
        job: '広告営業',
        sex: 1,
      },
      {
        id: '3',
        imageForCard: '/user3.png',
        imageForProfile: '/user3-large.png',
        imageForIcon: '',
        name: 'ゆり',
        age: '25',
        job: '美容師',
        sex: 1,
      },
    ],
  },
]
